name: CI

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
        node:
          - 18
          - 20
          - 22
          - 23
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - arch: x86
            node: 20
            os: windows-latest
          - arch: x86
            node: 22
            os: windows-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-02-21T09%3A43%3A46.292000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
          cache: npm
          cache-dependency-path: ./package.json
      - run: npm install
      - run: npm run lint
        if: matrix.os == 'ubuntu-latest' && matrix.node == 20 && matrix.arch == 'x64'
      - run: npm test
  coverage:
    if: false
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-02-21T09%3A43%3A46.292000Z@time-machines-npm.sealsecurity.io/
      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
